# kafka-docker-compose.yml
# https://github.com/wurstmeister/kafka-docker
# one zookeeper one broker
version: '2'
services:
  zookeeper:
    container_name: zookeeper1
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka1
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      # 생성할 Topic 정보 Topic_name:partition_cnt:replica_cnt
      KAFKA_CREATE_TOPICS: "test_topic:1:1"
      # Zookeeper info
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # kafka_2.12-2.3.0.tgz folder mount
      - ./Kafkaspace/kafka1/data:/kafka