---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"


## X-PACK security
#
#elasticsearch.hosts: ["http://elasticsearch:9200"]
#xpack.monitoring.enabled: true
#elasticsearch.username: elastic
#elasticsearch.password: ${LOGSTASH_INTERNAL_PASSWORD}